# action.yml
name: 'Sync Upstream Repo'
description: 'Keep upstream repositories in sync'
inputs:
  remote-repository: 
    description: 'Remote Repository URL'
    required: true
    default: 'https://github.com/heckelmann/test-src.git'
  remote-ref: 
    description: 'Remote ref to sync from'
    required: false
    default: 'master'
  target-repository: 
    description: 'Target Repository to sync to'
    required: false
    default: 'heckelmann/test-target'
  target-ref: 
    description: 'Target ref to sync to'
    required: false
    default: 'master'
  auth-token:    
    description: 'GitHub Token to push changes'
    required: true
    default: ''  
  rebase:    
    description: 'pull rebase - true will rebase'
    required: false
    default: 'false'       
outputs:
  sync-status: # id of output
    description: 'Was the sync successful'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.remote-repository }}
    - ${{ inputs.remote-ref }}
    - ${{ inputs.target-repository }}
    - ${{ inputs.target-ref }}
    - ${{ inputs.auth-token }}
    - ${{ inputs.rebase }}